### PR TITLE
adjusts tests location to be inside craterstats src folder

### PR DESCRIPTION
**Pull request by AndrewAnnex**
tests on the ci were failing I think because of the source layout of craterstats. This PR should restructure things to allow the action to run. 

@ggmichael please authorize the tests to run but do not merge until the tests pass

### CODE REVIEW

**Comment by AndrewAnnex** [comment]
Ah! the demo cmd file is not being packaged in sdist, I should be able to fix it quickly

**Comment by AndrewAnnex** [comment]
nope, nothing extra at this point. I'll keep iterating until I work out the solution

**Comment by AndrewAnnex** [comment]
@ggmichael it looks like the file `craterstats/sample/c7_Michael-et-al-2021.scc` is missing from the project. If you push the file to the repository then this pr can be merged

**Comment by ggmichael** [comment]
ok - that file's there

**Comment by ggmichael** [comment]
argh - sorry!

**Comment by ggmichael** [comment]
great - it worked. Thanks for this.

**Comment by ggmichael** [comment]
So where do those demo plots end up? I don't see them

**Comment by AndrewAnnex** [comment]
You should see them of the page for each run as a section called “Artifacts”



-Andrew Annex

**Comment by ggmichael** [comment]
I found it - thanks!

**Pull request merged**
